import ResponsiveNavbar from "@/components/Navbar";
import "./globals.css";
import ResponsiveFooter from "@/components/Footer";
import { ReduxProvider } from "@/lib/redux/provider";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "snapcart home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <ResponsiveNavbar />
        <ReduxProvider className="flex-1">{children}</ReduxProvider>
        <Toaster position="top-center" reverseOrder={false} />
        <ResponsiveFooter />
      </body>
    </html>
  );
}
