import ResponsiveNavbar from "@/components/Navbar";
import "./globals.css";
import ResponsiveFooter from "@/components/Footer";

export const metadata = {
  title: "snapcart home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <ResponsiveNavbar />

        {/* Main content fills the remaining space */}
        <main className="flex-1">{children}</main>

        <ResponsiveFooter />
      </body>
    </html>
  );
}
